BANNED_NAMES = ('me',)

MAX_LENGHT_CHAR_FIELD = 254

MAX_LENGHT_NAME_FIELD = 150

MAX_LENGHT_EMEIL_FIELD = 254

MAX_LENGHT_SLUG_FIELD = 50

MAX_STR_LENGTH = 25

MAX_LENGHT_COLOR_FIELD = 7

MIN_VALUE = 1

MIN_VALUE_MSG = 'Значение этого поля должно быть больше 1.'

MAX_VALUE = 32000
