version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: food-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  frontend:
    container_name: food-front
    build: ./frontend
    command: cp -r /app/build/. /frontend_static
    volumes:
      - static:/frontend_static
  
  backend:
    container_name: food-back
    build: ./backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - frontend
      - db
    command: sh -c "sleep 5 && ./run.sh"
    restart: always

  gateway:
    container_name: food-gateway
    build: ./gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/web/media
    ports:
      - 8080:80
    restart: always