version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: food-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  frontend:
    container_name: food-front
    build: ./frontend
    volumes:
      - static:/frontend_static
  
  backend:
    container_name: food-back
    build: ./backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - frontend
      - db
    command: >
      sh -c "python manage.py collectstatic --noinput
             cp -r /app/static/. /backend_static/static/
             python manage.py migrate
             python manage.py load_ingredients
             python manage.py load_tags
             python manage.py addsuperuser
             gunicorn --bind 0.0.0.0:8080 foodgram.wsgi"
    restart: always

  gateway:
    container_name: food-gateway
    build: ./gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 8080:80
    restart: always